server:
  port: 8083
  servlet:
    context-path: /boke

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Yu1078015403

  redis:
    host: 127.0.0.1
    port: 6379
    password: Yu1078015403
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

mybatis:
  mapper-locations:  classpath:/mapper/*.xml
  type-aliases-package: com.example.demo.entity

